language: python
sudo: false
python:
  - "2.6"
  - "2.7"
  - "3.3"
install:
  - python setup.py sdist --formats=gztar -k
  - find ./dist -iname "*.tar.gz" -print0 | xargs -0 pip install
  - pip install coveralls
script:
  - coverage run --source=namedparser setup.py test
after_success:
  - coveralls
